composer.json, composer.lock
This patch has been applied and released via tag [release-1.5.3.hf1](https://github.com/uwmweb/uwmcms/releases/tag/release-1.5.3.hf1)
=> UWM-CMS: Apply patch for Drupal core - Critical - Remote Code Execution - SA-CORE-2018-004

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page-tabs.js, docroot/themes/custom/uwmbase/uwmbase.libraries.yml, docroot/themes/custom/uwmbase/uwmbase.theme
https://www.wrike.com/open.htm?id=368713230
This resolves the issue of clinic cards being cached across location search results and featured clinics, i.e. showing the wrong card version on one or the other.
=> hotfix/featured-clinics-caching > master

config/envs/dev/stevie/devel.settings.yml, config/envs/local/stevie/devel.settings.yml
Add the `devel.settings` config to the `local` and `dev` environment splits, where the devel module is enabled
=> maintenance/prod-configuration-sync > master (3)

config/stevie/core.entity_form_display.paragraph.half_wide_hero.default.yml, config/stevie/core.entity_view_display.paragraph.half_wide_hero.default.yml, config/stevie/field.field.paragraph.half_wide_hero.uwm_text_2.yml, config/stevie/field.storage.paragraph.uwm_text_2.yml
This adds a rich text field, "Additional Text", to the hero for Med Service pages, to account for the additional text in the hero on Urgent Care and Emergency Medicine pages.
**Note:** This work is also included in the `feature/hero-med-services-styling-368077494` branch. I've created this separate branch in case we want to deploy the fields sooner for content work.
See:
=> feature/hero-med-services-additional-text-field > master

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-body.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-directions.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-providers.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs.html.twig
https://www.wrike.com/open.htm?id=372572500
* Removes clinic page accent headers: Services, Clinic Overview, Care Providers, Directions & Parking
* Connect left side Overview link to an empty anchor tag (instead of the Overview accent header)
=> feature/clinic-remove-accent-headers-372572500 > stage

docroot/themes/custom/uwmbase/src/scss/init/mixins/mixins.scss
This reverts a global change to the cta buttons font-weight, that occurred when moving the styling into a mixin.
=> UWM-BASE: remove font-weight 600 from .btn-cta and button-cta() default

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-body.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-directions.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs-providers.html.twig, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.tabs.html.twig, docroot/themes/custom/uwmbase/components/navigation/nav-tabs/nav-tabs.scss
https://www.wrike.com/open.htm?id=372572500
* Removes clinic page accent headers: Services, Clinic Overview, Care Providers, Directions & Parking
* Connect left side Overview link to an empty anchor tag (instead of the Overview accent header)
* Adjusts spacing around h2s in the page per Emily's review
=> feature/clinic-remove-accent-headers-372572500 > master

docroot/themes/custom/uwmbase/components/card/card.scss
UWM-BASE: move .card-body ul/ol padding to be specific to .specialty-intro-cards, not all cards
=> hotfix/card-ul-padding > master

blt/blt.yml, blt/ci.blt.yml
https://www.wrike.com/open.htm?id=380797549
Configure blt to **not** run `tests:frontend:run` command in builds. It was triggering starting the php internal server, which was timing out/erroring strangely. But we don't have any front-end tests, so the build step is unnecessary.
=> hotfix/travis-builds > stage (skip BLT front end tests command)

blt/blt.yml, blt/ci.blt.yml
https://www.wrike.com/open.htm?id=380797549
Configure blt to **not** run `tests:frontend:run` command in builds. It was triggering starting the php internal server, which was timing out/erroring strangely. But we don't have any front-end tests, so the build step is unnecessary.
=> hotfix/travis-builds > master (skip BLT front end tests command)

docroot/themes/custom/uwmbase/components/card/card.scss, docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss, docroot/themes/custom/uwmbase/components/grid-paragraph/grid-paragraph.scss, docroot/themes/custom/uwmbase/components/view-medical-specialties-for-services/view-medical-specialties-for-services.scss, docroot/themes/custom/uwmbase/src/scss/base/_sections.scss, docroot/themes/custom/uwmbase/src/scss/init/mixins/mixins.scss, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-grid.html.twig, docroot/themes/custom/uwmbase/templates/views/views-view-unformatted--uwm-medical-specialties-for-service--block-1.html.twig, docroot/themes/custom/uwmbase/uwmbase.theme
Service & Specialty page finalization tweaks, round 2
* Cards in Grid - remove Bootstrap .card-deck wrapper, which set all cards in single row, regardless of total number; instead dynamically handle number of cards per row (including responsive) based on total number of cards. This applies generically to Grid/Cards components, not only to the intro cards on Service/Specialty pages.
* More spacing tweaks for grey-background section
=> feature/finalize-service-specialty-pages > stage (2)

docroot/themes/custom/uwmbase/components/accordion/accordion.twig, docroot/themes/custom/uwmbase/components/anchor-scroll/anchor-scroll.js, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-cta-link.html.twig, docroot/themes/custom/uwmbase/uwmbase.info.yml
Extend jump link (UWM CTA paragraph) handling to scroll to and open an accordion section, and go to a different page and scroll to an element there.
This is used on a few service pages.
https://www.wrike.com/open.htm?id=387611464
=> hotfix/accordion-jump-link-38761146 > stage

docroot/themes/custom/uwmbase/components/accordion/accordion.twig, docroot/themes/custom/uwmbase/components/anchor-scroll/anchor-scroll.js, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-cta-link.html.twig, docroot/themes/custom/uwmbase/uwmbase.info.yml
Extend jump link (UWM CTA paragraph) handling to scroll to and open an accordion section, and go to a different page and scroll to an element there.
This is used on a few service pages.
https://www.wrike.com/open.htm?id=387611464
=> hotfix/accordion-jump-link-38761146 > master

docroot/modules/custom/uwmed_uwmcms_search/uwmed_uwmcms_search.module
UWM-STEVIE: workaround for duplicated 'expertise' query parameter in 'See all Locations' button links to pre-filtered search
=> hotfix/search-query-param-dupe-workaround > master

docs/webforms/2019-09-25/webform.webform.acn_request.yml
https://www.wrike.com/open.htm?id=402091929
(Webform config is managed in the admin ui directly now, not in config in the repo, so this change is only a copy of the updated webform config in `docs/webforms` directory.)
This is a record of changing the ACN Request form to redirect to full URL of a basic page node for the confirmation page, so we ensure using `www.uwmedicine.org` domain instead of the form api redirecting to `stevie.cms.uwmedicine.org`.
=> [docs only] hotfix/aco-form-confirmation-redirect-402091929 > master

config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml
Update provider view mode display configs with missing fields. (Not sure why this didn't come up in previous local diffs...)
=> hotfix/config-provider-fields-view-modes-2019-10-22 > stage

config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml
Update provider view mode display configs with missing fields. (Not sure why this didn't come up in previous local diffs...)
=> hotfix/config-provider-fields-view-modes-2019-10-22 > master

config/stevie/config_ignore.settings.yml
This reverts the change to the dashed list format merged to master here:
https://github.com/uwmweb/uwmcms/pull/1270/files#diff-b74391091b7a121de029087090c2045e
=> UWM-STEVIE: hotfix restore config_ignore settings with numeric index format

config/stevie/core.entity_form_display.node.res_clinic.default.yml, config/stevie/core.entity_view_display.media.video.default.yml, config/stevie/core.entity_view_display.media.video_embed.default.yml, config/stevie/core.entity_view_display.node.res_clinic.card.yml, config/stevie/core.entity_view_display.node.res_clinic.default.yml, config/stevie/core.entity_view_display.node.res_clinic.full.yml, config/stevie/core.entity_view_display.node.res_clinic.teaser.yml, config/stevie/field.field.node.res_clinic.field_res_location_note.yml, config/stevie/field.field.node.res_provider.field_res_image.yml, config/stevie/field.storage.node.field_res_location_note.yml, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.html.twig, docroot/themes/custom/uwmbase/uwmbase.theme
Set Video Embed and Remote Video media entities to NOT autoplay in Default view mode
(Applies globally to the site, per Daniel request)
Example: https://www.uwmedicine.org/airliftnw/protocols-training
=> hotfix/videos-disable-autoplay > stage

config/stevie/core.entity_view_display.media.video.default.yml, config/stevie/core.entity_view_display.media.video_embed.default.yml
Set Video Embed and Remote Video media entities to NOT autoplay in Default view mode
(Applies globally to the site, per Daniel request)
Example: https://www.uwmedicine.org/airliftnw/protocols-training
=> hotfix/videos-disable-autoplay > master

.composer_show.out, composer.lock, config/calendar/config_ignore.settings.yml, config/chew/config_ignore.settings.yml, config/contentrepo/config_ignore.settings.yml, config/default/config_ignore.settings.yml, config/default/config_split.config_split.prod.yml, config/envs/prod/default/config_ignore.settings.yml, config/envs/prod/stevie/config_ignore.settings.yml, config/envs/stage/default/config_ignore.settings.yml, config/huddle/config_ignore.settings.yml, config/stevie/config_ignore.settings.yml, config/stevie/config_split.config_split.prod.yml, config/stevie/core.entity_form_display.node.res_clinic.default.yml, config/stevie/core.entity_form_display.paragraph.hours_for_day.default.yml, config/stevie/core.entity_form_display.paragraph.hours_of_operation.default.yml, drush/sites/calendar.site.yml, drush/sites/huddle.site.yml
1. Per updating Config Ignore module to 2.2 in #1456:
Change format of `config_ignore.settings` config to use dashed list instead of numerically indexed. This aligns with the change in the module: https://www.drupal.org/project/config_ignore/issues/3002832
2. Updates the Drush aliases for `calendar` and `huddle` sites to point `test` to Acquia stage environment, rather than RA.
3. Removes env splits of `config_ignore.settings` on `stevie` and `default` (CMS) - these were unnecessary, because the same configs are being ignored across environments.
=> maintenance/config-ignore-2.2-settings-format > stage

config/calendar/config_ignore.settings.yml, config/chew/config_ignore.settings.yml, config/contentrepo/config_ignore.settings.yml, config/default/config_ignore.settings.yml, config/default/config_split.config_split.prod.yml, config/envs/prod/default/config_ignore.settings.yml, config/envs/prod/stevie/config_ignore.settings.yml, config/envs/stage/default/config_ignore.settings.yml, config/huddle/config_ignore.settings.yml, config/stevie/config_ignore.settings.yml, config/stevie/config_split.config_split.prod.yml, drush/sites/calendar.site.yml, drush/sites/huddle.site.yml
1. Per updating Config Ignore module to 2.2 in #1456:
Change format of `config_ignore.settings` config to use dashed list instead of numerically indexed. This aligns with the change in the module: https://www.drupal.org/project/config_ignore/issues/3002832
2. Updates the Drush aliases for `calendar` and `huddle` sites to point `test` to Acquia stage environment, rather than RA.
3. Removes env splits of `config_ignore.settings` on `stevie` and `default` (CMS) - these were unnecessary, because the same configs are being ignored across environments.
=> maintenance/config-ignore-2.2-settings-format > master

config/stevie/migrate_plus.migration.uwm_res_providers_import_providers.yml
Temporarily disable importing appointment field values on providers Res => Stevie migration, in prep for releasing appointment work:
- field_res_isacceptingnewpts
- field_res_ser_id
- field_res_is_open_scheduling
(Other fields are not yet in the migration:
- field_res_visit_type_id
- field_res_isacceptingreturnpts
- field_res_is_direct_scheduling)
=> hotfix/temp-disable-appt-fields-migration > master

config/stevie/field.field.paragraph.uwm_link_with_icon.field_uwm_link.yml, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-link-with-icon--uwm-card.html.twig, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-link-with-icon.html.twig
Fixes this fatal error:
```
TypeError: Argument 2 passed to Drupal\uwmcs_extension\TwigExtension::getCustomLinkRenderArray() must be of the type string, null given, called in /mnt/tmp/uwmed/php_storage/twig/d995f99/stevie/twig/5e3b2ff6367f8_paragraph--uwm-link-with-_ezfiZm7FNwDJdrdg-yYbxfbca/sA9rBoR3hal06ycCWV0YuEMXHiDAwdHhzqKjHSSELBI.php
```
which occurred when a Link with Icon paragraph was present, but its Link field was left empty. The template had assumed the link field would be populated and ended up passing a NULL value for the URL to the `uwm_cta_link()` twig function.
Also sets the Link field on the paragraph type to be required, since it does not make sense to have a Link with Icon paragraph without the link.
=> hotfix/link-with-icon-paragraph-empty-fatal > stage

config/stevie/field.field.paragraph.uwm_link_with_icon.field_uwm_link.yml, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-link-with-icon--uwm-card.html.twig, docroot/themes/custom/uwmbase/templates/paragraphs/paragraph--uwm-link-with-icon.html.twig
Fixes this fatal error:
```
TypeError: Argument 2 passed to Drupal\uwmcs_extension\TwigExtension::getCustomLinkRenderArray() must be of the type string, null given, called in /mnt/tmp/uwmed/php_storage/twig/d995f99/stevie/twig/5e3b2ff6367f8_paragraph--uwm-link-with-_ezfiZm7FNwDJdrdg-yYbxfbca/sA9rBoR3hal06ycCWV0YuEMXHiDAwdHhzqKjHSSELBI.php
```
which occurred when a Link with Icon paragraph was present, but its Link field was left empty. The template had assumed the link field would be populated and ended up passing a NULL value for the URL to the `uwm_cta_link()` twig function.
Also sets the Link field on the paragraph type to be required, since it does not make sense to have a Link with Icon paragraph without the link. This prevents the possibility of creating this scenario going forward, …
=> hotfix/link-with-icon-paragraph-empty-fatal > master

docroot/themes/custom/uwmbase/components/provider-page/node--res-provider--education.html.twig, docroot/themes/custom/uwmbase/uwmbase.theme
…f the old IM json_packet field values. This can be turned on safely anytime although, will not show provider education unless those fields are present on the node.
=> [___HOLD___] UWM-STEVIE: Template updates that enable display of PUMA certs and education (to MASTER)

docroot/themes/custom/uwmbase/components/appointment-flow/uwm-ecare-open-schedule-embedded-widget.js, docroot/themes/custom/uwmbase/components/modal/modal-appointment.scss
css-hide the button added by EmbeddedWidgetController.js meant to toggle the open scheduling widget to full-screen in mobile - it does not work correctly within our modal
=> hotfix/open-sched-widget-remove-mobile-fullscreen-toggle > stage

docroot/themes/custom/uwmbase/components/appointment-flow/uwm-ecare-open-schedule-embedded-widget.js, docroot/themes/custom/uwmbase/components/modal/modal-appointment.scss
css-hide the button added by EmbeddedWidgetController.js meant to toggle the open scheduling widget to full-screen in mobile - it does not work correctly within our modal
=> hotfix/open-sched-widget-remove-mobile-fullscreen-toggle > master

docroot/themes/custom/uwmbase/components/modal/modal-appointment.js
https://www.wrike.com/open.htm?id=464317056
iPhone and iPad on iOS 12 and below do not scroll iframe content. This prevents the user from being able to fully interact with the open scheduling widget in iframe.
As a workaround, detect these devices in JS and when moving to the open scheduling widget, redirect to the widget url, rather than staying on our page with the widget in the iframe.
=> hotfix/open-sched-widget-ios-scrolling > stage

docroot/themes/custom/uwmbase/components/modal/modal-appointment.js
https://www.wrike.com/open.htm?id=464317056
iPhone and iPad on iOS 12 and below do not scroll iframe content. This prevents the user from being able to fully interact with the open scheduling widget in iframe.
As a workaround, detect these devices in JS and when moving to the open scheduling widget, redirect to the widget url, rather than staying on our page with the widget in the iframe.
=> hotfix/open-sched-widget-ios-scrolling > master

docroot/modules/custom/uwmcs_ecare_scheduling/uwmcs_ecare_scheduling.module, patches/drupal-htaccess/htaccess_prepend_contents.htaccess
https://www.wrike.com/open.htm?id=459580168
Deploy curl request for open scheduling widget to stage, with eCare test env - which has the undesired setting and thus should send the 'X-Frame-Options: SAMEORIGIN' header - so we can confirm that we're catching the case we don't want.
(This includes temporary debug messages)
=> feature/open-scheduling-iframe-check-459580168 > stage (1)

docroot/modules/custom/uwmcs_ecare_scheduling/uwmcs_ecare_scheduling.module
Change open scheduling widget curl check to use:
- ecare prod url (because test url is not available except by vpn)
- temporarily the 'Server: Microsoft-IIS/8.5' header, which we expect to be there, to force our case to trigger to true
=> feature/open-scheduling-iframe-check-459580168 > stage (2)

docroot/modules/custom/uwmcs_ecare_scheduling/src/EventSubscriber/ResProviderMigrationSubscriber.php, docroot/modules/custom/uwmcs_ecare_scheduling/uwmcs_ecare_scheduling.module
Restore the email notification of missing visit types for Reservoir-to-Stevie migration in this branch, until ready to fully delete it.
=> del-reservoir/epic-imports-442058015 > stage (3)

config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml, config/stevie/core.entity_view_display.node.uwm_homepage.default.yml, config/stevie/core.entity_view_display.node.uwm_homepage.search_result.yml, config/stevie/core.entity_view_display.node.uwm_homepage.teaser.yml, config/stevie/core.entity_view_display.node.uwm_hub_page.default.yml, config/stevie/core.entity_view_display.node.uwm_hub_page.search_result.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.default.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.full.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.search_result.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.teaser.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.default.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.full.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.teaser.yml, config/stevie/core.entity_view_display.node.uwm_quiz.default.yml, config/stevie/core.entity_view_display.node.uwm_quiz.teaser.yml
- ensure Content Owner and Subject Matter Experts fields are hidden on all content type displays
- misc missing field dependencies and hidden fields on displays
=> hotfix/hide-content-owner-sme-fields > stage

config/stevie/core.entity_view_display.node.res_clinic.card.yml, config/stevie/core.entity_view_display.node.res_clinic.search_result.yml, config/stevie/core.entity_view_display.node.res_clinic.teaser.yml, config/stevie/search_api.index.uwm_general_search_api_index.yml, config/stevie/search_api.index.uwm_locations_geo_search_api_index.yml
* add missing `field_uwm_banner_content` as hidden on clinic displays
* add missing dependencies on `field_uwm_content_owner`, `field_uwm_subject_matter_experts` on clinic displays
* remove extra blank line at end of two of the search index configs, as it kept coming up as a change in local config exports
=> hotfix/config-update-clinic-displays > master

config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml, config/stevie/core.entity_view_display.node.uwm_homepage.default.yml, config/stevie/core.entity_view_display.node.uwm_homepage.search_result.yml, config/stevie/core.entity_view_display.node.uwm_homepage.teaser.yml, config/stevie/core.entity_view_display.node.uwm_hub_page.default.yml, config/stevie/core.entity_view_display.node.uwm_hub_page.search_result.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.default.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.full.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.search_result.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.teaser.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.default.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.full.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.teaser.yml, config/stevie/core.entity_view_display.node.uwm_quiz.default.yml, config/stevie/core.entity_view_display.node.uwm_quiz.teaser.yml
- ensure Content Owner and Subject Matter Experts fields are hidden on all content type displays
- misc missing field dependencies and hidden fields on displays
=> hotfix/hide-content-owner-sme-fields > master
