docroot/modules/custom/uwmcs_reader/src/Controller/UwmFetcher.php, docroot/modules/custom/uwmcs_reader/uwmcs_reader.module
IM endpoint switched to https-only and some of our data wasn't getting loaded since we were pointing to http:// endpoints.
=> UWM-CMS: Switch to https for IM requests

config/stevie/migrate_plus.migration.uwm_res_providers_import_providers.yml, docroot/modules/custom/uwm_res_import/config/optional/migrate_plus.migration.uwm_res_providers_import_providers.yml, docroot/themes/custom/uwmbase/components/clinic-page/clinic-page-tabs.js, docroot/themes/custom/uwmbase/components/provider-page/provider-page.scss, docroot/themes/custom/uwmbase/uwmbase.libraries.yml, docroot/themes/custom/uwmbase/uwmbase.theme
This resolves the issue of clinic cards being cached across location search results and featured clinics, i.e. showing the wrong card version on one or the other.
=> hotfix/featured-clinics-caching > stage

composer.json, composer.lock, config/stevie/config_ignore.settings.yml, config/stevie/core.extension.yml, config/stevie/lightning_core.versions.yml
…ng structured json metadata in page headers for Google search ranking.
=> UWM-STEVIE: Adding modules to support later SEO and structured meta-tag work  (to MASTER)

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss
…aragraphs at the bottom of location pages.
=> UWM-RESERVOIR: Increasing the padding around headers that appear in p… 359764323 (to MASTER)

config/envs/dev/stevie/devel.settings.yml, config/envs/local/stevie/devel.settings.yml
In devel.settings config (on local and dev), added two values that were missing - compared to module's original config
=> maintenance/prod-configuration-sync > master (4)

config/stevie/migrate_plus.migration.uwm_res_clinics_import_clinics.yml, docroot/modules/custom/uwm_res_import/config/optional/migrate_plus.migration.uwm_res_clinics_import_clinics.yml
=> UWM-RESERVOIR: Adding migration field for Is Hospital flag from Reser… (to MASTER)

docroot/sites/stevie/settings.php
=> UWM-RESERVOIR: Use local Solr for local Search API (to MASTER)

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss, docroot/themes/custom/uwmbase/components/navigation/nav-tabs/nav-tabs.scss
Updates spacing around clinic page headers, per design review
=> feature/clinic-remove-accent-headers-372572500 > stage (2)

docroot/themes/custom/uwmbase/src/scss/base/_typography.scss
Global h2 padding tweak, per design review
=> feature/med-services-sections-paragraph-359361502 > stage (2)

config/stevie/core.entity_view_display.node.uwm_medical_service.full.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.search_result.yml, config/stevie/core.entity_view_display.node.uwm_medical_service.teaser.yml, config/stevie/core.entity_view_display.node.uwm_medical_specialty.default.yml, config/stevie/core.entity_view_display.paragraph.half_wide_hero.default.yml, config/stevie/core.entity_view_display.paragraph.uwm_sections_medical_services.default.yml, docroot/themes/custom/uwmbase/components/clinic-card/clinic-card.scss
…red clinics on medical services pages.
=> Features/service page featured locations 359363917 (to STAGE)

docroot/themes/custom/uwmbase/components/clinic-page/clinic-page.scss
(to confirm on dev with Emily before merge)
Per design review round 2: more spacing tweaks for clinic page sections and headers after removing accent headers
=> feature/clinic-remove-accent-headers-372572500 > stage (3)

config/stevie/core.extension.yml, config/stevie/lightning_core.versions.yml, config/stevie/metatag.metatag_defaults.global.yml
=> UWM-RESERVOIR: Adding basic configuration for SEO schema metadata (to DEVELOP)

docroot/themes/custom/uwmbase/components/provider-page/node--res-provider.html.twig, docroot/themes/custom/uwmbase/templates/fields/field--node--field-res-medical-services--res-clinic.html.twig
=> UWM-RESERVOIR: Update label for medical specialties terms 371402464 (to MASTER)

config/stevie/core.entity_view_display.paragraph.uwm_sections_medical_services.default.yml
UWM-STEVIE: correct config export of entity_view_display.paragraph.uwm_sections_medical_services - reorder a few lines
=> hotfix/config-uwm-sections-medical-services-view-display > master

docroot/modules/custom/uwmcs_utils/uwmcs_utils.module
…a, prod) to administrators in the admin-toolbar.
=> UWM-CMS: Show current environment in administrator toolbar (to MASTER)

docroot/themes/custom/uwmbase/components/card/card.scss
UWM-BASE: remove duplicated ul/ol selector in card.scss
=> hotfix/card-ul-padding > master (2)

config/chew/config_ignore.settings.yml, config/default/config_ignore.settings.yml, config/huddle/config_ignore.settings.yml, config/stevie/config_ignore.settings.yml
…ig/development/ignore, so that webform content can be managed by editors.
=> UWM-CMS: Adding webforms to the config-ignore settings (to MASTER)

docroot/sites/default/settings.php, docroot/sites/stevie/settings.php, docroot/sites/uwm-require-auth-cookie-page-blocker.php
=> Features/block pre-production form 377211022 (to STAGE)

docroot/sites/default/settings.php
=> UWM-CMS: Triggering updating in stevie settings to put auth cookie pr… (to STAGE)

patches/drupal-htaccess/htaccess.patch
=> UWM-CMS: Alias lp directory microsites so URLs are preserved after migrating (to MASTER)

docroot/sites/uwm-require-auth-cookie-page-blocker.php
=> UWM-CMS: Bypass Varnish on dev and stage, if missing custom cookie (to MASTER)

composer.json, composer.lock
* Remove module requirement and repository reference for `uwm_paragraphs` module (which was unused)
* Add SMTP module (for Rick - Email a Patient form)
* Add a patch for Metatag and patch for Schema Metatag (for Tory - clinic structured data)
=> features/composer-needs-2019-09-10 > master

docroot/modules/custom/uwmed_uwmcms_search/uwmed_uwmcms_search.module, docroot/themes/custom/uwmbase/templates/views/views-view--uwm-locations-geo-search--page-1.html.twig, docroot/themes/custom/uwmbase/templates/views/views-view--uwm-providers-search--page-1.html.twig
https://www.wrike.com/open.htm?id=354416863
Alter the h1 page title and <title> for Provider and Location search results based on:
* specialty term
* keywords
* number of results
Remove the white box above the results that previously displayed number of results.
=> features/search-page-title-results-354416863 > stage

docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicAddress.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicImage.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicMedicalSpecialty.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicMember.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicName.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicTelephone.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicType.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicUrl.php, docroot/modules/custom/uwmed_schema_clinic/uwmed_schema_clinic.module
This resolves two issues with the structured data on clinic nodes:
https://www.wrike.com/open.htm?id=396861447
'department' for Urgent Care hours requires 'image'
https://www.wrike.com/open.htm?id=396809551
'member' value was empty array for clinics with no providers (i.e. hospitals)
=> features/clinics-structured-data-351781802 > stage (2)

docroot/modules/custom/uwmed_uwmcms_search/uwmed_uwmcms_search.module, docroot/themes/custom/uwmbase/templates/views/views-view--uwm-locations-geo-search--page-1.html.twig, docroot/themes/custom/uwmbase/templates/views/views-view--uwm-providers-search--page-1.html.twig
https://www.wrike.com/open.htm?id=354416863
Alter the h1 page title and <head> <title> for Provider and Location search results based on:
* specialty term
* keywords
* number of results
Remove the white box above the results that previously displayed number of results.
=> features/search-page-title-results-354416863 > master

docroot/modules/custom/uwmcs_utils/uwmcs_utils.module, docroot/themes/custom/uwmbase/components/clinic-page/node--res-clinic--full.html.twig
…showing new See all locations CTA. Allows removing greedy logic check at the top of the CTA's section.
=> UWM-CMS: Updating clinic-page is-building CTA logic (to MASTER)

patches/drupal-htaccess/htaccess_prepend_contents.htaccess
…g is used for  default proxy.
=> UWM-CMS: Correcting htaccess typo for setting default proxy (to MASTER)

docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicPotentialAction.php, docroot/modules/custom/uwmed_schema_clinic/src/Plugin/metatag/Tag/SchemaMedicalClinicUrl.php
For clinic structured data PotentialAction and Url values, replace 'stevie.cms.' with 'www.'
=> hotfix/clinics-structured-data-stevie-urls > master

docroot/.htaccess.20190927
… //education.uwmedicine.org. Note there are Drupal redirects which happened to redirect some of these pages to the School of Medicine.
=> UWM-CMS: Redirecting all education paths to the education intranet (to MASTER)

docroot/modules/custom/uwmcs_utils/uwmcs_utils.module
On clinic nodes that are hospitals, remove the Providers entity ref field because it may make the form too large to submit and be handled by server
=> feature/connect-provider-hospital-398629574 > stage (2)

config/stevie/core.entity_view_display.node.res_provider.provider_card.yml
UWM-STEVIE: update provider_card view mode display settings with recently added taxonomy-related fields
=> hotfix/provider-card-config-2019-10-21 > stage

config/stevie/core.entity_view_display.node.res_provider.provider_card.yml
Update provider_card view mode display settings with recently added taxonomy-related fields
=> hotfix/provider-card-config-2019-10-21 > master

docroot/themes/custom/uwmbase/uwmbase.theme
This reverts commit dc5a7d58792ddd99724fe82939aee6646c83625f.
=> UWM-STEVIE: Revert "UWM-STEVIE: Sort taxonomy terms by name"

patches/drupal-htaccess/htaccess_prepend_contents.htaccess
… name to https://www.uwmedicine.org/locations/northwest-ent-associates.
=> UWM-CMS: htaccess update to redirect www.nwentassociates.org (to MASTER)

patches/drupal-htaccess/htaccess_prepend_contents.htaccess
…heir new www.uwmedicine.org pages.
=> UWM-CMS: Htaccess redirects for eastside.uwmedicine.org pages (to MASTER)

.composer_show.out, composer.json, composer.lock, config/default/core.base_field_override.node.content_spotlight.status.yml, config/default/core.base_field_override.node.fact_page.status.yml, config/default/core.base_field_override.node.landing_page.promote.yml, config/default/core.base_field_override.node.landing_page.status.yml, config/default/core.base_field_override.node.page.status.yml, config/default/core.base_field_override.node.quiz.status.yml, config/default/core.base_field_override.node.uwm_clinic.status.yml, config/default/core.base_field_override.node.uwm_medical_specialty.status.yml, config/default/core.base_field_override.node.uwm_provider.status.yml, config/default/core.extension.yml, config/default/d8_google_optimize_hide_page.settings.yml, config/default/lightning_core.versions.yml, config/default/node.type.condition_spotlight.yml, config/default/node.type.content_spotlight.yml, config/default/node.type.fact_page.yml, config/default/node.type.homepage.yml, config/default/node.type.landing_page.yml, config/default/node.type.page.yml, config/default/node.type.quiz.yml, config/default/node.type.uwm_clinic.yml, config/default/node.type.uwm_medical_service.yml, config/default/node.type.uwm_medical_specialty.yml, config/default/node.type.uwm_provider.yml, config/default/node_revision_delete.settings.yml
…d subsite, so old revisions will be pruned on @uwmed cron runs.
=> UWM-CMS: Adding node_revision_delete to old uwmed (to MASTER)

config/stevie/views.view.frontpage.yml
=> UWM-STEVIE: Disabling the view Front, so /node no longer shows a node… (to MASTER)

config/stevie/core.entity_form_display.node.res_provider.default.yml, config/stevie/core.entity_form_display.taxonomy_term.visit_type_labels.default.yml, config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml, config/stevie/core.entity_view_display.taxonomy_term.visit_type_labels.default.yml, config/stevie/field.field.node.res_provider.field_res_is_direct_scheduling.yml, config/stevie/field.field.node.res_provider.field_res_isacceptingreturnpts.yml, config/stevie/field.field.node.res_provider.field_res_visit_type_id.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_description.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_ecare_desc.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_ecare_name.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_name.yml, config/stevie/field.storage.node.field_res_is_direct_scheduling.yml, config/stevie/field.storage.node.field_res_isacceptingreturnpts.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_description.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_ecare_desc.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_ecare_name.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_name.yml, config/stevie/taxonomy.vocabulary.visit_type_labels.yml
Add configs for appointment work:
- Provider fields (is accepting returning, is enabled for direct scheduling)
- Visit Type Labels taxonomy vocabulary and fields
=> feature/provider-appointment-configs > stage

config/stevie/views.view.uwm_admin_provider_manager.yml
=> UWM-STEVIE: Updating admin provider report (to MASTER)

config/stevie/core.entity_form_display.node.res_provider.default.yml, config/stevie/core.entity_form_display.taxonomy_term.visit_type_labels.default.yml, config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml, config/stevie/core.entity_view_display.taxonomy_term.visit_type_labels.default.yml, config/stevie/field.field.node.res_provider.field_res_is_direct_scheduling.yml, config/stevie/field.field.node.res_provider.field_res_isacceptingreturnpts.yml, config/stevie/field.field.node.res_provider.field_res_visit_type_id.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_description.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_ecare_desc.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_ecare_name.yml, config/stevie/field.field.taxonomy_term.visit_type_labels.field_visit_type_name.yml, config/stevie/field.storage.node.field_res_is_direct_scheduling.yml, config/stevie/field.storage.node.field_res_isacceptingreturnpts.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_description.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_ecare_desc.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_ecare_name.yml, config/stevie/field.storage.taxonomy_term.field_visit_type_name.yml, config/stevie/taxonomy.vocabulary.visit_type_labels.yml
Add configs for appointment work:
* Provider fields (is accepting returning, is enabled for direct scheduling)
* Visit Type Labels taxonomy vocabulary and fields
=> feature/provider-appointment-configs > master

config/stevie/core.extension.yml, config/stevie/lightning_core.versions.yml, config/stevie/migrate_plus.migration.uwm_res_tax__buildings.yml, config/stevie/migrate_plus.migration.uwm_res_tax__campuses.yml, docroot/modules/custom/uwm_admin_providers/src/Form/UnpublishProvidersForm.php, docroot/modules/custom/uwm_admin_providers/uwm_admin_providers.info.yml, docroot/modules/custom/uwm_admin_providers/uwm_admin_providers.module, docroot/modules/custom/uwm_admin_providers/uwm_admin_providers.routing.yml, docroot/modules/custom/uwm_bulk_process_content/uwm_bulk_process_content.info.yml, docroot/modules/custom/uwm_res_import/config/optional/migrate_plus.migration.uwm_res_tax__buildings.yml, docroot/modules/custom/uwm_res_import/config/optional/migrate_plus.migration.uwm_res_tax__campuses.yml
Add uwm_admin_providers module, to hold general admin utilities for providers, e.g. altering views from Reservoir
=> del-reservoir/uwm-admin-providers-module > master

.composer_show.out, composer.json, composer.lock
Reservoir port: add migrate_source_csv module - 2.x branch rather than 3.x due to dependency requirements
=> del-reservoir/migrate-source-csv-module > master

patches/drupal-htaccess/htaccess_prepend_contents.htaccess
=> UWM-CMS: Htaccess redirect so uwmedicine.com is redirected… . (to MASTER)

config/stevie/core.entity_form_display.node.res_clinic.default.yml, config/stevie/core.entity_form_display.node.res_provider.default.yml, config/stevie/field.field.node.res_clinic.field_featured.yml, config/stevie/field.field.node.res_clinic.field_res_feat_clinics_view_all.yml
A few tweaks on the clinic and provider forms:
* Clinic - move 'Featured' field to 'Location' grouping for clarity
* Clinic - update help text on a couple of fields
* Clinic & Provider - disable Moderation State field for now (because it does not cooperate with Corresponding Entity References)
=> hotfix/clinic-featured-field-grouping > master

docroot/modules/custom/uwmcs_utils/uwmcs_utils.module
https://www.wrike.com/open.htm?id=442066953
On clinic nodes that are hospitals:
- update admin messaging explaining inability to edit Providers ref field
- add listing of referenced providers for convenience
=> del-reservoir/provider-hospital-442066953 > stage

config/stevie/core.entity_form_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.autocomplete.yml, config/stevie/core.entity_view_display.node.res_provider.card.yml, config/stevie/core.entity_view_display.node.res_provider.default.yml, config/stevie/core.entity_view_display.node.res_provider.provider_card.yml, config/stevie/core.entity_view_display.node.res_provider.search_result.yml, config/stevie/core.entity_view_display.node.res_provider.teaser.yml, config/stevie/field.field.node.res_provider.field_uwm_edw_boardcerts.yml, config/stevie/field.field.node.res_provider.field_uwm_edw_education.yml, config/stevie/field.storage.node.field_uwm_edw_boardcerts.yml, config/stevie/field.storage.node.field_uwm_edw_education.yml, config/stevie/migrate_plus.migration.uwm_res_providers_import_providers.yml, docroot/.htaccess.20200130, docroot/modules/custom/uwm_res_import/config/optional/migrate_plus.migration.uwm_res_providers_import_providers.yml
… can be migrated to providers.
=> UWM-STEVIE: Adding fields and migration work for storing PUMA data (to MASTER)

docroot/themes/custom/uwmbase/components/modal/modal-appointment.js
Tweak: update resetting open scheduling URL to account for link-out case.
=> hotfix/open-sched-widget-ios-scrolling > stage (2)

config/stevie/views.view.uwm_providers_scheduling.yml, config/stevie/views.view.uwm_providers_scheduling_bulk_edit.yml
=> del-reservoir/epic-imports-442058015 > stage (2) (tweaks)

docroot/modules/custom/uwmcs_utils/uwmcs_utils.module
https://www.wrike.com/open.htm?id=442066953
On clinic nodes that are hospitals:
* update admin messaging explaining inability to edit Providers ref field
* add listing of referenced providers for convenience
=> del-reservoir/provider-hospital-442066953 > master
